version: "2.3"

services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    environment:
     GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://DOMAIN';
      nginx['redirect_http_to_https'] = false;
      nginx['listen_https'] = false;
      nginx['listen_port'] = 80;
      gitlab_rails['gitlab_shell_ssh_port'] = 22022;
      gitlab_rails['initial_root_password'] = '[APP_PASSWORD]';
      gitlab_rails['smtp_enable'] = true;
      gitlab_rails['smtp_address'] = '172.17.0.1';
      gitlab_rails['smtp_port'] = 25;
      gitlab_rails['smtp_domain'] = '[DOMAIN]';
      gitlab_rails['smtp_tls'] = false;
      gitlab_rails['smtp_openssl_verify_mode'] = 'none';
      gitlab_rails['smtp_enable_starttls_auto'] = false;
      gitlab_rails['smtp_ssl'] = false;
      gitlab_rails['smtp_force_ssl'] = false;
      gitlab_rails['gitlab_email_from'] = '[DOMAIN]@vm.elestio.app';
      gitlab_rails['gitlab_email_reply_to'] = '[DOMAIN]@vm.elestio.app';
      gitlab_rails['gitlab_signup_enabled'] = false
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    restart: always
    ports:
      - "172.17.0.1:8080:80"
      - "22022:22"